#!/bin/bash
# GitHub Ops Skill - Config Setup Script
# Generates .claude/github-config.yaml with your project's board IDs

set -e

echo "=== GitHub Ops Skill - Config Setup ==="
echo ""

# Check gh is installed and authenticated
if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) not installed"
    echo "Install: brew install gh"
    exit 1
fi

if ! gh auth status &> /dev/null; then
    echo "Error: Not authenticated with GitHub"
    echo "Run: gh auth login"
    exit 1
fi

# Get current repo info
REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner' 2>/dev/null || echo "")
if [ -z "$REPO" ]; then
    echo "Warning: Not in a git repo or repo not on GitHub"
    read -p "Enter repo (owner/name): " REPO
fi

OWNER=$(echo "$REPO" | cut -d'/' -f1)
echo "Repo: $REPO"
echo "Owner: $OWNER"
echo ""

# Get default branch
DEFAULT_BASE=$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name' 2>/dev/null || echo "main")
echo "Default branch: $DEFAULT_BASE"
echo ""

# List projects and let user pick
echo "=== Available Projects ==="
echo ""

PROJECTS_JSON=$(gh project list --owner "$OWNER" --format json)
PROJECT_COUNT=$(echo "$PROJECTS_JSON" | jq '.projects | length')

if [ "$PROJECT_COUNT" -eq 0 ]; then
    echo "No projects found for $OWNER"
    echo "Create a project at: https://github.com/orgs/$OWNER/projects"
    exit 1
fi

# Display numbered list
echo "$PROJECTS_JSON" | jq -r '.projects | to_entries[] | "  [\(.key + 1)] \(.value.title) (#\(.value.number))"'
echo ""

# Get user selection
while true; do
    read -p "Select a project [1-$PROJECT_COUNT]: " SELECTION

    if [[ "$SELECTION" =~ ^[0-9]+$ ]] && [ "$SELECTION" -ge 1 ] && [ "$SELECTION" -le "$PROJECT_COUNT" ]; then
        break
    else
        echo "Invalid selection. Enter a number between 1 and $PROJECT_COUNT"
    fi
done

# Get selected project details
INDEX=$((SELECTION - 1))
PROJECT_NUMBER=$(echo "$PROJECTS_JSON" | jq -r ".projects[$INDEX].number")
PROJECT_TITLE=$(echo "$PROJECTS_JSON" | jq -r ".projects[$INDEX].title")

echo ""
echo "Selected: $PROJECT_TITLE (#$PROJECT_NUMBER)"

# Get project ID
echo ""
echo "Fetching project details..."
PROJECT_ID=$(gh project view "$PROJECT_NUMBER" --owner "$OWNER" --format json --jq '.id')
echo "Project ID: $PROJECT_ID"

# Get fields
echo ""
echo "Fetching field IDs..."
FIELDS_JSON=$(gh project field-list "$PROJECT_NUMBER" --owner "$OWNER" --format json)

# Find Status field
STATUS_FIELD_ID=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .id')

if [ -z "$STATUS_FIELD_ID" ]; then
    echo "Warning: No 'Status' field found in project"
    echo "Available fields:"
    echo "$FIELDS_JSON" | jq -r '.fields[].name'
    STATUS_FIELD_ID="FILL_IN_STATUS_FIELD_ID"
else
    echo "Status Field ID: $STATUS_FIELD_ID"
fi

# Get status options
echo ""
echo "=== Status Options ==="
STATUS_OPTIONS=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .options[]? | "\(.name): \(.id)"')

if [ -z "$STATUS_OPTIONS" ]; then
    echo "No status options found"
else
    echo "$STATUS_OPTIONS"
fi

# Build statuses object - try to auto-map common status names
echo ""
echo "Auto-mapping status options..."

BACKLOG_ID=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .options[]? | select(.name | test("backlog|Backlog"; "i")) | .id' | head -1)
TODO_ID=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .options[]? | select(.name | test("^todo$|^Todo$|^TODO$|^To Do$|^To do$"; "i")) | .id' | head -1)
IN_PROGRESS_ID=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .options[]? | select(.name | test("progress|Progress|doing|Doing|In Progress"; "i")) | .id' | head -1)
IN_REVIEW_ID=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .options[]? | select(.name | test("review|Review"; "i")) | .id' | head -1)
DONE_ID=$(echo "$FIELDS_JSON" | jq -r '.fields[] | select(.name == "Status") | .options[]? | select(.name | test("done|Done|complete|Complete|Completed"; "i")) | .id' | head -1)

# Generate config file
CONFIG_FILE="github-config.yaml"
echo ""
echo "=== Generating $CONFIG_FILE ==="

cat > "$CONFIG_FILE" << EOF
# GitHub Operations Skill - Project Configuration
# Generated by setup-config.sh on $(date)
# Project: $PROJECT_TITLE

# Repository info
repo: "$REPO"
owner: "$OWNER"
default_base: "$DEFAULT_BASE"

# Project board settings
project_number: $PROJECT_NUMBER
project_id: "$PROJECT_ID"
status_field_id: "$STATUS_FIELD_ID"

# Status column option IDs
# (auto-mapped from your project's status options)
statuses:
  backlog: "${BACKLOG_ID:-FILL_IN}"
  todo: "${TODO_ID:-FILL_IN}"
  in_progress: "${IN_PROGRESS_ID:-FILL_IN}"
  in_review: "${IN_REVIEW_ID:-FILL_IN}"
  done: "${DONE_ID:-FILL_IN}"

# ============================================
# Raw status options from your project:
# (use these to fill in any FILL_IN values above)
# ============================================
$(echo "$STATUS_OPTIONS" | sed 's/^/# /')
EOF

echo ""
echo "✓ Config generated: $CONFIG_FILE"
echo ""

# Check for unmapped statuses
FILL_COUNT=$(grep -c "FILL_IN" "$CONFIG_FILE" || echo "0")
if [ "$FILL_COUNT" -gt 0 ]; then
    echo "⚠️  $FILL_COUNT status(es) couldn't be auto-mapped."
    echo "   Edit $CONFIG_FILE and replace FILL_IN with correct IDs."
    echo "   Reference the 'Raw status options' comments at the bottom."
else
    echo "✓ All statuses auto-mapped!"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
cat "$CONFIG_FILE"
echo ""
echo "---"
echo "Next steps:"
echo "1. Review the config above"
echo "2. Commit: git add github-config.yaml && git commit -m 'Add github ops config'"
echo "3. Use /github in Claude Code"
